"""initial_migration

Revision ID: a4b5e1b64b77
Revises: 
Create Date: 2025-01-15 17:12:24.141691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a4b5e1b64b77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_records', sa.Column('url', sa.String(length=500), nullable=False))
    op.add_column('image_records', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('image_records', sa.Column('status', sa.String(length=20), nullable=True))
    op.alter_column('image_records', 'process_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('image_records', 'result',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('image_records', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('image_records', 'file_path')
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('image_records', sa.Column('file_path', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('image_records', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('image_records', 'result',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.alter_column('image_records', 'process_type',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('image_records', 'status')
    op.drop_column('image_records', 'source')
    op.drop_column('image_records', 'url')
    # ### end Alembic commands ###
